### ISSUE TITLE
Build fails on M2 Mac (ARM64) due to undefined symbol '_ImageKernelConvolution'

### ISSUE THREAD

**Issue by judah-caruso** [onyx-lang/pkg-raylib#1]
Looks like v5.0 release of raylib is missing `ImageKernelConvolution` which causes `onyx run build --generate-foreign-info` to fail when adding raylib as a dependency.

Removing line 368 in `module.onyx` or replacing `macos/libraylib.a` with one built from master fixes this. 

Can submit a PR for either, dealer's choice.

**Comment by brendanfh** [comment]
Interesting. I just copied everything from their `raylib.h` header and figured it was right.

If you have it working on your system, a PR is definitely welcome! I had to borrow a Mac to get things working initially, so I do not have a way to test it now, so a PR is the better route to know it works.
